### ISSUE TITLE
Lucee throwing 500 error

### ISSUE THREAD

**Issue by MikeRankin** [writecodedrinkcoffee/vagrant-lemtl#1]
I've tried this a few times and each time I get the same result:

HTTP Status 500 -
type Exception report
message
description The server encountered an internal error that prevented it from fulfilling this request.
exception
javax.servlet.ServletException
    lucee.commons.io.log.log4j.Log4jUtil.getAppender(Unknown Source)
    lucee.commons.io.log.LoggerAndSourceData.getLog(Unknown Source)
    lucee.runtime.config.ConfigImpl.getLog(Unknown Source)
    lucee.runtime.config.ConfigWebFactory.loadLoggers(Unknown Source)
    lucee.runtime.config.ConfigWebFactory.load(Unknown Source)
    lucee.runtime.config.ConfigWebFactory.newInstance(Unknown Source)
    lucee.runtime.engine.CFMLEngineImpl.loadJSPFactory(Unknown Source)
    lucee.runtime.engine.CFMLEngineImpl.addServletConfig(Unknown Source)
    lucee.loader.engine.CFMLEngineFactory.getInstance(Unknown Source)
    lucee.loader.servlet.CFMLServlet.init(Unknown Source)
    org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
    org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
    org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
    org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
    org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
    org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    java.lang.Thread.run(Thread.java:745)
note The full stack trace of the root cause is available in the Apache Tomcat/7.0.52 (Ubuntu) logs.

Apache Tomcat/7.0.52 (Ubuntu)

I'm not sure exactly what the problem is.  The box comes up okay with the normal update guest-extensions business.

I'm able to ssh to the box and look around.  

I tried replacing the WEB-INF with a fresh download from the Lucee site with no change.  

I've tried restart services and reinstalling tomcat with no change.

I tried putting the WEB-INF folder from another lucee project I'm working that I know works, and it does change the error message to:
Lucee [4.5.1.003] - Error (java.io.IOException)
Message No such file or directory
Cause   java.io.IOException
Java Stacktrace 
No such file or directory
at java.io.UnixFileSystem.createFileExclusively(Native Method):-2
at java.io.File.createNewFile(File.java:1006):1006
at lucee.commons.io.res.type.file.FileResource.getOutputStream(Unknown Source):-1
at lucee.commons.io.res.type.file.FileResource.getOutputStream(Unknown Source):-1
at lucee.commons.io.IOUtil.copy(Unknown Source):-1
at lucee.runtime.compiler.CFMLCompilerImpl.compile(Unknown Source):-1
at lucee.runtime.PageSourceImpl._compile(Unknown Source):-1
at lucee.runtime.PageSourceImpl.compile(Unknown Source):-1
at lucee.runtime.PageSourceImpl.loadPhysical(Unknown Source):-1
at lucee.runtime.PageSourceImpl.loadPage(Unknown Source):-1
at lucee.runtime.PageSourceImpl.loadPage(Unknown Source):-1
at lucee.runtime.PageContextImpl.doInclude(Unknown Source):-1
at lucee.runtime.PageContextImpl.doInclude(Unknown Source):-1
at lucee.runtime.PageContextImpl.handlePageException(Unknown Source):-1
at lucee.runtime.listener.ModernAppListener.onError(Unknown Source):-1
at lucee.runtime.PageContextImpl.execute(Unknown Source):-1
at lucee.runtime.PageContextImpl.execute(Unknown Source):-1
at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(Unknown Source):-1
at lucee.loader.servlet.CFMLServlet.service(Unknown Source):-1
at javax.servlet.http.HttpServlet.service(HttpServlet.java:727):727
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303):303
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208):208
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220):220
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122):122
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170):170
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98):98
at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950):950
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116):116
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408):408
at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040):1040
at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607):607
at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313):313
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145):1145
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615):615
at java.lang.Thread.run(Thread.java:745):745

I'm not sure if that is better or worse.  At least it's a Lucee generated error.  Static files are served fine.

I'm starting to think that this might be some sort of permissions issue.

Any ideas?

**Comment by mikesprague** [comment]
If you think it's permissions, you could try changing the Vagrantfile (on lines 28 & 29) to

``` ruby
synced_webroot_owner = "tomcat7"
synced_webroot_group = "tomcat7"
```

and then running: `$ vagrant reload --provision`

I haven't started with a fresh copy in a while. I'll check it out on another computer tonight and see if I can replicate your issue. If I can, I may have some more insight for you; I'd give the above a shot in the meantime.

**Comment by mikesprague** [comment]
Quick follow-up... Tried a clean install on a computer that had never run this project and it spun up with no problems.

Some more info might be useful. What's your host OS? Are you hitting via hostname or ip address? Is it the default index.cfm file from this project or are you running your own code? Have you tried browsing to the Lucee Web and/or Server admin?

**Comment by mikesprague** [comment]
I'm tagging this as a question and closing it until/if it's confirmed to be an issue with the project, itself.

**Comment by atadams** [comment]
I'm having the same issue on Mac Yosemite. Changing the webroot owner and group to "tomcat7" and reloading resolved the issue.

**Comment by MikeRankin** [comment]
That seems strange though, doesn't it.  Why would the vm behave differently based on the host in terms of its local file permissions.  Maybe it has something to do with the way vagrant is mirroring that directory.  If we change the vagrantfile, do you think it will still work on windows?

**Comment by MikeRankin** [comment]
As of version 1.2.2, this is running without issue on os x Yosemite.  I'm not sure what fixed it.  Possibly the nginx upgrade or the latest os x patch.

**Comment by mikesprague** [comment]
Glad to hear it's working now. Not sure what it could have been and I develop mainly on Linux (and Windows) and didn't have access to a Mac to play around and try to help. 

Sometimes a simple `vagrant reload --provision` resolves issues like these. I presume it's related to the speed/memory of the host machine but it doesn't always seem to have the box fully provisioned when the terminal indicates it's up.

In any case, good news that it's running for you now.
